---
- hosts: server
  become: true

  tasks:
    - name: Create mountpoint
      ansible.builtin.file:
        state: directory
        path: /mnt/data/
        owner: marcin
        group: marcin
        mode: 0777

    - name: Add 1.5Tb disk to fstab
      ansible.builtin.lineinfile:
        path: /etc/fstab
        state: present
        regexp: "^/dev/disk/by-partuuid/1f7c9e25-2b31-7347-a8b8-31425a8ba58f"
        line: "/dev/disk/by-partuuid/1f7c9e25-2b31-7347-a8b8-31425a8ba58f   /mnt/data/    ext4    defaults    0   1"

    - name: Reown & Chmod it after mounting
      ansible.builtin.file:
        state: directory
        path: /mnt/data/
        owner: marcin
        group: marcin
        mode: 0777
