---
- hosts: server
  become: true

  tasks:
    - name: Disable swap
      ansible.builtin.command: swapoff -a

    - name: Remove swap from fstab
      ansible.builtin.lineinfile:
        dest: /etc/fstab
        regexp: swap
        state: absent

    - name: Ensure we need to install k3s
      ansible.builtin.command: which k3s
      register: k3s_installed
      ignore_errors: yes

    - name: Install k3s using Rancher script
      ansible.builtin.shell: curl -sfL https://get.k3s.io | sh -
      when: k3s_installed is failed

    - name: Configure traefik to expose the dashboard
      ansible.builtin.copy:
        src: files/var/lib/rancher/k3s/server/manifests/traefik-config.yaml
        dest: /var/lib/rancher/k3s/server/manifests/traefik-config.yaml
        owner: root
        group: root
        mode: 0600
